### PR TITLE
Add Documentation

### PR DESCRIPTION
**Pull request by alexlyttle**
Solves Issue #26.

Please review and let me know if you have any suggestions before merging.

## Changes

* Adds documentation using `sphinx` and the `readthedocs` theme
* Publishes documentation to https://jaxns.readthedocs.io
* Installation instructions added
* Example notebooks added and catagorised
* API documentation built automatically with [Sphinx AutoAPI](https://sphinx-autoapi.readthedocs.io/en/latest/)
* Uses a `sphinx` extension to parse Google- (or numpy-) style docstrings
* Automatically pulls the parameter types from Python type hinting when not in docstring
* Some changes to docstrings to fix sphinx warnings and errors.

## To Do

* [ ] Review https://jaxns.readthedocs.io

* [ ] Some mathematics in docstrings have already been rewritten to render with Latex (see [sphinx docs](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#math) for details on how).
  E.g. the API for [fourier.py](https://github.com/alexlyttle/jaxns/blob/docs/jaxns/modules/experimental/fourier/fourier.py) renders in the docs like [this](https://jaxns.readthedocs.io/en/latest/api/jaxns/modules/experimental/fourier/fourier/index.html#jaxns.modules.experimental.fourier.fourier.fourier).
  * [ ] Check the maths notation makes sense 
* [ ] Add @Joshuaalbert as maintainer of https://jaxns.readthedocs.io (just need an email address)

## Future (after merge)

* Transfer https://jaxns.readthedocs.io to pull from `Joshuaalbert/jaxns` not `alexlyttle/jaxns`
* Docstrings should be written consistently in the Google style to make AutoAPI work best
  * They need tidying up, I am happy to help with this in a future PR.
  * E.g. function parameters should be written like this
    ```
    Args:
        parameter (type): description
    ```
    but in `jaxns` it is often written as
    ```
    Args:
        parameter: type, description
    ```
    which `sphinx` can't parse properly.
  * Note: if `(type)` is omitted and type hinting is used for `parameter` then the type is automatically detected by `sphinx`
* Add Getting Started section to the User Guide?

### CODE REVIEW

**Review by Joshuaalbert — APPROVED** [review]
LGTM

**Comment by Joshuaalbert** [comment]
I'll gradually rework the docstrings as I prepare to release this next version. Thanks for getting this going @alexlyttle!

**Comment by Joshuaalbert** [comment]
@alexlyttle I updated the docs in `main` branch but the readthedocs did not trigger a rebuild. How do we set up a webhook to rebuild on push to main?

**Comment by Joshuaalbert** [comment]
Note `master` has been renamed to `main` in jaxns so perhaps when you set it up you used `master` and it's not rebuilding because it still looks for that? Could you transfer the readthedocs project to my account btw?

**Comment by alexlyttle** [comment]
@Joshuaalbert I have changed the settings on the readthedocs end to fix this. It was because the branch was renamed. I have also sent you an invite to be a maintainer too, hopefully you get something by email shortly.

**Pull request merged**
